-- Run this once in Supabase SQL Editor to store map marker click events.

create table if not exists public.place_marker_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  place_id text not null,
  place_name text,
  category text,
  address text,
  latitude double precision,
  longitude double precision,
  source text not null default 'map_marker',
  created_at timestamptz not null default now()
);

alter table public.place_marker_events enable row level security;

drop policy if exists "anonymous users can create place marker events" on public.place_marker_events;
create policy "anonymous users can create place marker events"
on public.place_marker_events for insert
to anon
with check (user_id is null);

drop policy if exists "users can create place marker events" on public.place_marker_events;
create policy "users can create place marker events"
on public.place_marker_events for insert
to authenticated
with check (user_id is null or (select auth.uid()) = user_id);

drop policy if exists "users can read their own place marker events" on public.place_marker_events;
create policy "users can read their own place marker events"
on public.place_marker_events for select
to authenticated
using ((select auth.uid()) = user_id);

create index if not exists place_marker_events_created_at_idx on public.place_marker_events(created_at desc);
create index if not exists place_marker_events_place_id_idx on public.place_marker_events(place_id);
create index if not exists place_marker_events_user_id_idx on public.place_marker_events(user_id);

create or replace view public.place_marker_events_kst as
select
  id,
  user_id,
  place_id,
  place_name,
  category,
  address,
  latitude,
  longitude,
  source,
  created_at,
  timezone('Asia/Seoul', created_at) as created_at_kst
from public.place_marker_events;

grant insert on public.place_marker_events to anon;
grant select, insert on public.place_marker_events to authenticated;
grant select on public.place_marker_events_kst to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
