create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  photo_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.community_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.place_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  place_name text not null,
  address text,
  menus jsonb not null default '[]'::jsonb,
  photo_count integer not null default 0,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  place_id text not null,
  category text,
  place_name text,
  saving_amount integer not null default 0 check (saving_amount >= 0),
  visited_at timestamptz not null default now()
);

create table if not exists public.place_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  place_id text not null,
  place_name text,
  category text,
  created_at timestamptz not null default now(),
  unique (user_id, place_id)
);

create table if not exists public.community_likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id text not null,
  created_at timestamptz not null default now(),
  unique (user_id, post_id)
);

create table if not exists public.comment_likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  comment_id text not null,
  created_at timestamptz not null default now(),
  unique (user_id, comment_id)
);

create table if not exists public.groupbuy_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null,
  product_title text,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.groupbuy_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  product_id text,
  product_title text,
  event_type text not null check (event_type in ('favorite', 'unfavorite', 'participate', 'share')),
  created_at timestamptz not null default now()
);

create table if not exists public.auth_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in ('open_login', 'open_signup', 'login_complete', 'signup_complete')),
  entry_source text,
  return_page text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.community_posts enable row level security;
alter table public.comments enable row level security;
alter table public.place_requests enable row level security;
alter table public.visits enable row level security;
alter table public.place_favorites enable row level security;
alter table public.community_likes enable row level security;
alter table public.comment_likes enable row level security;
alter table public.groupbuy_favorites enable row level security;
alter table public.groupbuy_events enable row level security;
alter table public.auth_events enable row level security;

create policy "profiles are readable by authenticated users"
on public.profiles for select
to authenticated
using (true);

create policy "users can insert their own profile"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id);

create policy "users can update their own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "community posts are readable by authenticated users"
on public.community_posts for select
to authenticated
using (true);

create policy "users can create their own posts"
on public.community_posts for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "users can update their own posts"
on public.community_posts for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "users can delete their own posts"
on public.community_posts for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "comments are readable by authenticated users"
on public.comments for select
to authenticated
using (true);

create policy "users can create their own comments"
on public.comments for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "users can update their own comments"
on public.comments for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "users can delete their own comments"
on public.comments for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "users can create their own place requests"
on public.place_requests for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "users can read their own place requests"
on public.place_requests for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "users can update their pending place requests"
on public.place_requests for update
to authenticated
using ((select auth.uid()) = user_id and status = 'pending')
with check ((select auth.uid()) = user_id and status = 'pending');

create policy "users can delete their pending place requests"
on public.place_requests for delete
to authenticated
using ((select auth.uid()) = user_id and status = 'pending');

create policy "users can create their own visits"
on public.visits for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "users can read their own visits"
on public.visits for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "users can manage their own place favorites"
on public.place_favorites for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "users can manage their own community likes"
on public.community_likes for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "users can manage their own comment likes"
on public.comment_likes for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "users can manage their own groupbuy favorites"
on public.groupbuy_favorites for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "users can create groupbuy events"
on public.groupbuy_events for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "users can read their own groupbuy events"
on public.groupbuy_events for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "users can create their own auth events"
on public.auth_events for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "anonymous users can create auth events"
on public.auth_events for insert
to anon
with check (user_id is null);

create policy "users can read their own auth events"
on public.auth_events for select
to authenticated
using ((select auth.uid()) = user_id);

create index if not exists community_posts_user_id_idx on public.community_posts(user_id);
create index if not exists comments_post_id_idx on public.comments(post_id);
create index if not exists comments_user_id_idx on public.comments(user_id);
create index if not exists place_requests_user_id_idx on public.place_requests(user_id);
create index if not exists visits_user_id_visited_at_idx on public.visits(user_id, visited_at desc);
create index if not exists place_favorites_user_id_idx on public.place_favorites(user_id);
create index if not exists groupbuy_favorites_user_id_idx on public.groupbuy_favorites(user_id);
create index if not exists groupbuy_events_user_id_created_at_idx on public.groupbuy_events(user_id, created_at desc);
create index if not exists auth_events_user_id_created_at_idx on public.auth_events(user_id, created_at desc);

create or replace function public.get_my_saving_stats()
returns table (
  total_saving bigint,
  monthly_saving bigint,
  monthly_visit_count bigint
)
language sql
stable
as $$
  select
    coalesce(sum(saving_amount), 0)::bigint as total_saving,
    coalesce(
      sum(saving_amount) filter (
        where visited_at >= date_trunc('month', now())
          and visited_at < date_trunc('month', now()) + interval '1 month'
      ),
      0
    )::bigint as monthly_saving,
    count(*) filter (
      where visited_at >= date_trunc('month', now())
        and visited_at < date_trunc('month', now()) + interval '1 month'
    )::bigint as monthly_visit_count
  from public.visits
  where user_id = (select auth.uid());
$$;


grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.community_posts to authenticated;
grant select, insert, update, delete on public.comments to authenticated;
grant select, insert, update, delete on public.place_requests to authenticated;
grant select, insert on public.visits to authenticated;
grant select, insert, update, delete on public.place_favorites to authenticated;
grant select, insert, update, delete on public.community_likes to authenticated;
grant select, insert, update, delete on public.comment_likes to authenticated;
grant select, insert, update, delete on public.groupbuy_favorites to authenticated;
grant select, insert on public.groupbuy_events to authenticated;
grant select, insert on public.auth_events to authenticated;
grant insert on public.auth_events to anon;
grant usage, select on all sequences in schema public to authenticated;
grant usage, select on all sequences in schema public to anon;
grant execute on function public.get_my_saving_stats() to authenticated;
